In [1]:
from scipy import linalg
import numpy as np
from itertools import combinations
import pandas as pd
from string import ascii_uppercase

In [2]:
A = np.array([[1,1,1,0,0],
              [-2,1,0,1,0],
              [2,1,0,0,1]])
b = np.array([4,2,6])
c = np.array([-1,-2,0,0,0])

In [3]:
temp = list()

for combo in combinations(range(A.shape[1]), A.shape[0]):
  n = list(set(range(A.shape[1])).difference(combo))
  B = A[:,combo]
  B_inv = linalg.inv(B)

  # test if B's vectors are linearly independent
  if not np.any(B_inv @ np.zeros(3)):
    sol = B_inv @ b

    cB = c[[combo]]
    cN = c[[n]]
    cost = round(sol @ cB, 3) # calculate cost
    flag = np.all(sol >= 0) # flag if solution meets psd constraints

    xB = [f"x{el + 1}={round(s,3)}" for el,s in zip(combo, sol)]
    xN = [f"x{el + 1}=0" for el in n]
    temp.append([xB, xN, cB, cN, cost, flag])

solutions = pd.DataFrame(temp, columns=['xB', 'xN', 'cB', 'cN', 'cost', 'Is Feasible'], index=list(ascii_uppercase[:len(temp)]))
solutions

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:12: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  if sys.path[0] == '':
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:13: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  del sys.path[0]

,xB,xN,cB,cN,cost,Is Feasible
A,"[x1=1.0, x2=4.0, x3=-1.0]","[x4=0, x5=0]","[-1, -2, 0]","[0, 0]",-9.000,False
B,"[x1=2.0, x2=2.0, x4=4.0]","[x3=0, x5=0]","[-1, -2, 0]","[0, 0]",-6.000,True
C,"[x1=0.667, x2=3.333, x5=1.333]","[x3=0, x4=0]","[-1, -2, 0]","[0, 0]",-7.333,True
D,"[x1=3.0, x3=1.0, x4=8.0]","[x2=0, x5=0]","[-1, 0, 0]","[-2, 0]",-3.000,True
E,"[x1=-1.0, x3=5.0, x5=8.0]","[x2=0, x4=0]","[-1, 0, 0]","[-2, 0]",1.000,False
F,"[x1=4.0, x4=10.0, x5=-2.0]","[x2=0, x3=0]","[-1, 0, 0]","[-2, 0]",-4.000,False
G,"[x2=6.0, x3=-2.0, x4=-4.0]","[x1=0, x5=0]","[-2, 0, 0]","[-1, 0]",-12.000,False
H,"[x2=2.0, x3=2.0, x5=4.0]","[x1=0, x4=0]","[-2, 0, 0]","[-1, 0]",-4.000,True
I,"[x2=4.0, x4=-2.0, x5=2.0]","[x1=0, x3=0]","[-2, 0, 0]","[-1, 0]",-8.000,False
J,"[x3=4.0, x4=2.0, x5=6.0]","[x1=0, x2=0]","[0, 0, 0]","[-1, -2]",0.000,True

In [4]:
solutions[solutions['Is Feasible']]

,xB,xN,cB,cN,cost,Is Feasible
B,"[x1=2.0, x2=2.0, x4=4.0]","[x3=0, x5=0]","[-1, -2, 0]","[0, 0]",-6.000,True
C,"[x1=0.667, x2=3.333, x5=1.333]","[x3=0, x4=0]","[-1, -2, 0]","[0, 0]",-7.333,True
D,"[x1=3.0, x3=1.0, x4=8.0]","[x2=0, x5=0]","[-1, 0, 0]","[-2, 0]",-3.000,True
H,"[x2=2.0, x3=2.0, x5=4.0]","[x1=0, x4=0]","[-2, 0, 0]","[-1, 0]",-4.000,True
J,"[x3=4.0, x4=2.0, x5=6.0]","[x1=0, x2=0]","[0, 0, 0]","[-1, -2]",0.000,True